### ISSUE TITLE
Why is Schema.MinItems int64 while Schema.MaxItems *int64?

### ISSUE THREAD

**Issue by JivanAmara** [jban332/kin-openapi#2]
This seems strange, is it a mistake?

https://github.com/jban332/kin-openapi/blob/master/openapi3/schema.go#L66

**Comment by fenollp** [comment]
Probably for the defaults semantics it provides:
* `minItems` as `int` defaults to `0`, which is the spec's allowed default
* `maxItems` as `int` defaults to `0` (like all ints) but that's a meaningful constraint. Having it as `*int` makes it default to `nil` and is transparently handled by Go when marshaling.

**Comment by JivanAmara** [comment]
:+1:
